# Installing nginx and starting the nginx service
- name: Install nginx and enable
  hosts: local
  connections: local
  become: yes #-b, root access
  task:
  - name: install nginx
    ansible.bultin.package: #installing the nginx package
    name: nginx
    state: present
  - name: start the nginx
    ansible.builtin.service: #starting the nginx service
    name: nginx
    state: started
    enable: yes #enabling the nginx

