- name: install and run nginx
  hosts: 172.31.42.197
  become: yes # -b
  tasks:
  - name: install nginx
    ansible.builtin.package:
      name: nginx
      state: present
  - name: start the nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes

# - name: install nginx and run
#   hosts: local
#   connections: local
#   become: yes #-b, root access
#   tasks:
#   - name: install nginx
#     ansible.bultin.package: #installing the nginx package
#       name: nginx
#       state: present
#   - name: start the nginx
#     ansible.builtin.service: #starting the nginx service
#       name: nginx
#       state: started
#       enable: yes #enabling the nginx

