- name: variables
  hosts: web
  vars:
    COURSES: "Devops and cloud"
    TIME: 120HRS
    TRAINER: Gopi
  tasks:
  - name: print the variable
    ansible.builtin.debug:
      msg: "course is {{ COURSES }} and timings are {{ TIME }} by {{ TRAINER }}"