- name: filters
  hosts: web
  tasks:
  - name: handle undefined variables
    ansible.builtin.debug:
      msg: "{{ person | default('gopi') }}"

  - name: convert string to list
    vars:
      fruits: "apple, banana, mango"
    ansible.builtin.debug:
      msg: "Fruits are: {{ fruits | split(',') }}"
